### ISSUE TITLE
Nordic input file examples?

### ISSUE THREAD

**Issue by McBaboulek** [saeedsltm/PyVelest#10]
As I understand, for the first working step of the program I need a "NORDIC" file to un PySelect3D/2D. Where is an example of such a file in the repository? When I use the example file from https://nordb.readthedocs.io/en/latest/nordic_desc.html all I get is a divide by zero error.

```
  File "/Users/marc/Desktop/pyVelest/tools/PySelect3D.py", line 296, in <module>
    w_mean  = w_mean / float(len(data))

ZeroDivisionError: float division by zero
```

**Comment by McBaboulek** [comment]
I've also tried 

https://github.com/SEISAN-EARTHQUAKE-ANALYSIS-SOFTWARE/SEISAN-manual/blob/033808c055545beabca0ca78e780d382c12f31e8/appendix/nordic-format.tex#L25-L39

and 

https://github.com/SEISAN-EARTHQUAKE-ANALYSIS-SOFTWARE/SEISAN-manual/blob/033808c055545beabca0ca78e780d382c12f31e8/appendix/nordic-format.tex#L45-L55

but the parser just crashes with different errors every time...

```
  File "/Users/marc/Desktop/pyVelest/tools/PySelect2D.py", line 132, in <module>
    S      = '%02d'%int(i[0][16:18].strip())

ValueError: invalid literal for int() with base 10: '6.'
```

**Comment by saeedsltm** [comment]
Dear @McBaboulek , sorry for my delay. You can find the input example file in tools directory (tools./initial.out).
