### ISSUE TITLE
_GEOSArea issue

### ISSUE THREAD

**Issue by Isaac0880** [saeedsltm/PyVelest#12]
Hello, I've been attempting to compile PyVelest.py using Python 2.7 on my MacBook Pro M2. I've tried various solutions, including restarting my MacBook Pro, but I'm still encountering issues. Does anyone have any suggestions on how to resolve this?

(base) isaacguerra@MacBook-Pro-de-Isaac PyVelest % python2 PyVelest.py
Traceback (most recent call last):
  File "PyVelest.py", line 26, in <module>
    from mpl_toolkits.basemap import Basemap
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/mpl_toolkits/basemap/__init__.py", line 53, in <module>
    import _geoslib
ImportError: dlopen(/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/_geoslib.so, 0x0002): symbol not found in flat namespace '_GEOSArea'

**Comment by McBaboulek** [comment]
May be l can help you. I rund it on Windows and on Mac . I usually use .Mac. I think l put on 2020 on Internet how it function on Windows .  Jean Marc BABOULEK Ruhr Uni Bochum Germany . Let us have an appointement. Von meinem iPhone gesendetAm 10.10.2023 um 23:34 schrieb Isaac0880 ***@***.***>:﻿
Hello, I've been attempting to compile PyVelest.py using Python 2.7 on my MacBook Pro M2. I've tried various solutions, including restarting my MacBook Pro, but I'm still encountering issues. Does anyone have any suggestions on how to resolve this?
(base) ***@***.*** PyVelest % python2 PyVelest.py
Traceback (most recent call last):
File "PyVelest.py", line 26, in 
from mpl_toolkits.basemap import Basemap
File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/mpl_toolkits/basemap/init.py", line 53, in 
import _geoslib
ImportError: dlopen(/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/_geoslib.so, 0x0002): symbol not found in flat namespace '_GEOSArea'

**Comment by Jos-sm** [comment]
I've managed to make Pyvelest work with Python 3.9, I think this is the easiest way to avoid Python 2.7, which is already obsolete. I don't really have the time, but I could share my code with you, although it's not very clean.

Sorry for my English, I'm french speaking.

**Comment by Isaac0880** [comment]
> I've managed to make Pyvelest work with Python 3.9, I think this is the easiest way to avoid Python 2.7, which is already obsolete. I don't really have the time, but I could share my code with you, although it's not very clean.
> 
> Sorry for my English, I'm french speaking.

Hello Jos, do not worry, my English is not good as well. If you can share your code I will really appreciate it. This is my email: iguerra@uwo.ca

**Comment by McBaboulek** [comment]
Is okay . Pas de soucis je parle aussi Français .  Du cous moi de mon côté j’excute sur python 2.  Mais mais ! J édite mon code sur python 3. Sa parais un peut flou . Je crois si vous allee sur GitHub McBaboulek ( Images)  vous pouvez voire quelque images. Ahh oui. On peut toujours s échanger les codes . C est une bonne idée . Juste besoin de peut de temps car mes travaux date de 2020- 2021 pour me rappeler ou ce trouve tell ou tell chose .  Bonne idée Am 11.10.2023 um 10:32 schrieb Jos ***@***.***>:﻿
I've managed to make Pyvelest work with Python 3.9, I think this is the easiest way to avoid Python 2.7, which is already obsolete. I don't really have the time, but I could share my code with you, although it's not very clean.
Sorry for my English, I'm french speaking.

**Comment by Jos-sm** [comment]
On peut discuter sur skype si t'as le temps.

**Comment by McBaboulek** [comment]
Bsr. Je m excuse j étais très prit c est dernier temps. Ahh oui bonne idée voici mon skype. Mboule91 ou Jean Marc Baboulek

**Comment by McBaboulek** [comment]
Hallo Joss cnt vas tu? La sante?
