### ISSUE TITLE
cite pyvelest

### ISSUE THREAD

**Issue by veronica-antunes** [saeedsltm/PyVelest#3]
Hi, I am using PyVelest to make some figures and now I would like to know how can I cite it. I checked on the website but I couldn't find this information. 

Cheers,
Verónica

**Comment by saeedsltm** [comment]
Dear Veronica,

Sorry for my long late to answer you, BTW regarding the citation, there is no outcome paper related to this code yet. So unfortunately there is nothing but GitHub!. May i ask did you use the code and what is your result?

Regards
