### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by HGeoAle** [saeedsltm/PyVelest#4]
Good day Saeedsltm.
Your code is amazing and just what I need for my university project. I cannot express how grateful I am that you have posted this.
I could run all the tools preparation modules so far, but when I try to run the main code PyVelest.py the next eerror occurs 

> +++ Enter Project Name: <Please use the name of velocity model you're using>
>
>initial.py
>
>+++ Read VELEST input parameters ...
>+++ Write VELEST control file ...
>+++ Plotting data statistics ...
>+++ Make synthetic velocity models ...
>+++ Run VELEST ...
>  --- 50 synthetic model(s) found ...
>   --- Run for synthetic model: 1
>   --- Run for synthetic model: 2
>   --- Run for synthetic model: 3
>   --- Run for synthetic model: 4
>   --- Run for synthetic model: 5
>   --- Run for synthetic model: 6
>   --- Run for synthetic model: 7
>   --- Run for synthetic model: 8
>   --- Run for synthetic model: 9
>   --- Run for synthetic model: 10
>   --- Run for synthetic model: 11
>   --- Run for synthetic model: 12
>   --- Run for synthetic model: 13
>   --- Run for synthetic model: 14
>   --- Run for synthetic model: 15
>   --- Run for synthetic model: 16
>   --- Run for synthetic model: 17
>   --- Run for synthetic model: 18
>   --- Run for synthetic model: 19
>   --- Run for synthetic model: 20
>   --- Run for synthetic model: 21
>   --- Run for synthetic model: 22
>   --- Run for synthetic model: 23
>   --- Run for synthetic model: 24
>   --- Run for synthetic model: 25
>   --- Run for synthetic model: 26
>   --- Run for synthetic model: 27
>   --- Run for synthetic model: 28
>   --- Run for synthetic model: 29
>   --- Run for synthetic model: 30
>   --- Run for synthetic model: 31
>   --- Run for synthetic model: 32
>    --- Run for synthetic model: 33
>    --- Run for synthetic model: 34
>    --- Run for synthetic model: 35
>    --- Run for synthetic model: 36
>    --- Run for synthetic model: 37
>    --- Run for synthetic model: 38
>    --- Run for synthetic model: 39
>    --- Run for synthetic model: 40
>    --- Run for synthetic model: 41
>    --- Run for synthetic model: 42
>    --- Run for synthetic model: 43
>    --- Run for synthetic model: 44
>    --- Run for synthetic model: 45
>    --- Run for synthetic model: 46
>    --- Run for synthetic model: 47
>    --- Run for synthetic model: 48
>    --- Run for synthetic model: 49
>    --- Run for synthetic model: 50
> +++ Analyse VELEST outputs ...
> +++ Plotting data statistics ...
> +++ Minimum model id: 5
> +++ Preparing reports ...
> At line 1645 of file tau.for (unit = 22, file = '/home/hugo/SEISAN/DAT/IASP91_linux.HED')
> Fortran runtime error: End of file
> 
> Error termination. Backtrace:
> #0  0x7f78cdbd12da in ???
> #1  0x7f78cdbd1ec5 in ???
> #2  0x7f78cdbd268d in ???
> #3  0x7f78cdd48a33 in ???
> #4  0x7f78cdd4936f in ???
> #5  0x7f78cdd49435 in ???
> #6  0x7f78cdd4bcec in ???
> #7  0x564638fd0ab0 in tabin_
> 	at /home/hugo/SEISAN/LIB/tau.for:1645
> #8  0x564638f5517e in hypocent_
> 	at /home/hugo/SEISAN/LIB/hyposub1.for:254
> #9  0x564638f754c5 in read_stat_mod_
> 	at /home/hugo/SEISAN/LIB/hyposub3.for:1299
> #10  0x564638f47396 in hypmain_
> 	at /home/hugo/SEISAN/LIB/hypmain.for:663
> #11  0x564638f42c95 in hyp
> 	at /home/hugo/SEISAN/PRO/hyp.for:25
> #12  0x564638f42e9e in main
> 	at /home/hugo/SEISAN/PRO/hyp.for:41
> Traceback (most recent call last):
>   File "PyVelest.py", line 3137, in <module>
>     start.mk_report()
>   File "PyVelest.py", line 1746, in mk_report
>     remove('gmap.cur.kml')
> OSError: [Errno 2] No such file or directory: 'gmap.cur.kml'"
 I can see the problem comes from SEISAN but I am not sure whats is wrong, do you have any idea of what could be the problem?

**Comment by HGeoAle** [comment]
I have solved this issue.
The problem is I am running SEISAN in a 64-bit Unix system.
As the SEISAN Manual says, In order to work correctly it is necessary to compile the file IASP91_linux.HED in the DAT directory of SEISAN. To do that, one has to run the program REMODL and SETBRN.

**Comment by saeedsltm** [comment]
Hi Hugo,

Glad to hear your issue was solved. Let me know if there is any other problem :) Good Luck.
