### ISSUE TITLE
Coordinates

### ISSUE THREAD

**Issue by HGeoAle** [saeedsltm/PyVelest#5]
Hello, 
this code looks amazing, it exactly what I need at the moment, I already tried to use it with my data but I have been struggling with it for a while.
I am getting this error:
`
+++ Enter Project Name: <Please use the name of velocity model you're using>

initial.mod

+++ Read VELEST input parameters ...
+++ Write VELEST control file ...
+++ Plotting data statistics ...
+++ Make synthetic velocity models ...
+++ Run VELEST ...
   --- 5 synthetic model(s) found ...
   --- Run for synthetic model: 1
STOP ...end...(VELEST was running in SINGLE-EVENT-OPTION)
   --- Run for synthetic model: 2
STOP ...end...(VELEST was running in SINGLE-EVENT-OPTION)
   --- Run for synthetic model: 3
STOP ...end...(VELEST was running in SINGLE-EVENT-OPTION)
   --- Run for synthetic model: 4
STOP ...end...(VELEST was running in SINGLE-EVENT-OPTION)
   --- Run for synthetic model: 5
STOP ...end...(VELEST was running in SINGLE-EVENT-OPTION)
+++ Analyse VELEST outputs ...
Traceback (most recent call last):
  File "PyVelest.py", line 3136, in <module>
    start.analyse_velest_res()
  File "PyVelest.py", line 767, in analyse_velest_res
    self.svel['P'][sm].append(p_vel)
UnboundLocalError: local variable 'p_vel' referenced before assignment`

I have been looking around and the problem it that Velest is not generating its output files, but it is not because it is running in single event mode, but because it crashes reading the inputs. 
after some test comparing to the sample data (that runs ok), the main difference is that my data is on the western hemisphere, I tried mirroring my coordinates to the east hemisphere and it runs partially ok until the program tries to generate the final plots, in this case i get this error:
`+++ Enter Project Name: <Please use the name of velocity model you're using>

initial.mod

+++ Read VELEST input parameters ...
+++ Write VELEST control file ...
+++ Plotting data statistics ...
+++ Make synthetic velocity models ...
+++ Run VELEST ...
   --- 5 synthetic model(s) found ...
   --- Run for synthetic model: 1
   --- Run for synthetic model: 2
   --- Run for synthetic model: 3
   --- Run for synthetic model: 4
   --- Run for synthetic model: 5
+++ Analyse VELEST outputs ...
+++ Plotting data statistics ...
+++ Minimum model id: 4
+++ Preparing reports ...
Note: The following floating-point exceptions are signalling: IEEE_UNDERFLOW_FLAG IEEE_DENORMAL
Note: The following floating-point exceptions are signalling: IEEE_UNDERFLOW_FLAG IEEE_DENORMAL
Note: The following floating-point exceptions are signalling: IEEE_UNDERFLOW_FLAG IEEE_DENORMAL
Note: The following floating-point exceptions are signalling: IEEE_UNDERFLOW_FLAG IEEE_DENORMAL
+++ Plotting final figures, Please wait ...
Traceback (most recent call last):
  File "PyVelest.py", line 3138, in <module>
    start.plot_final()
  File "PyVelest.py", line 2574, in plot_final
    self.lat_min, self.lat_max])
  File "PyVelest.py", line 2514, in extract_hyp
    vals, vecs            = eigsorted(cov)
  File "PyVelest.py", line 2443, in eigsorted
    vals, vecs = linalg.eigh(cov)
  File "/home/hugo/.local/lib/python2.7/site-packages/numpy/linalg/linalg.py", line 1456, in eigh
    w, vt = gufunc(a, signature=signature, extobj=extobj)
TypeError: No loop matching the specified signature and casting
was found for ufunc eigh_lo
`
in this case the problem was that my data doesn't have x-y error correlation data (I only have X, Y errors) , so the program crashes when tries to draw the error ellipses. I just edited this section of code and then it works. 

one more small problem was this:
![path_initial](https://user-images.githubusercontent.com/55607748/66786851-5f8a8580-eed1-11e9-9682-56dc5142f695.jpg)
the bottom of the vertical coverage path still to high even tho I defined to be at 10 KM in the topo file

also I would like to be able to use the program with right coordinates but somehow the input files for Velest are not created properly when the coordinates are with negative longitude. Maybe someone has been able to fix it?

**Comment by HGeoAle** [comment]
![velest_analytics_initial](https://user-images.githubusercontent.com/55607748/66787783-77afd400-eed4-11e9-8c74-0ab9ed0ef577.jpg)
When I modify the reference velocity model, this graph only shows me one of model results, so I cannot compare results.

**Comment by saeedsltm** [comment]
Dear Hugo,

Well,... thanks for all your tries :). Could you please send me some portion of your own data-set? Actually when i was writing the code i though that there might be some bugs if using western hemisphere, so maybe its time to sole this issue.

Regards

**Comment by McBaboulek** [comment]
Hello Hugo and Saeedsltm,
I am trying to start the programme but I have this problem: STOP ...end...(VELEST was running in SINGLE-EVENT-OPTION). How can I solve the problem.
Best Regards

**Comment by saeedsltm** [comment]
Dear @McBaboulek , my guess is number of earthquakes in control file (please check "neqs" parameter in par/par.dat) which might be differ from the actual size in your input NORDIC file (lets say select.out).

**Comment by McBaboulek** [comment]
Dear Saeedsltm, thanks for the feedback.

**Comment by McBaboulek** [comment]
Thanks for the replay. Please, how can l get the plot of the first step. “ Check if the output file "select.out" is created.” Yes l have the output, just the plot remains.

**Comment by McBaboulek** [comment]
Dear saeedsltm, Dear Hugo,
l have some difficulties with the program, especially with the level:
Traceback (most recent call last):
  File "PyVelest.py", line 3159, in <module>
    start.analyse_velest_res()
  File "PyVelest.py", line 834, in analyse_velest_res
    ax1.plot(x, [self.avg_abs_adj[nm][_][0] for _ in range(len(self.avg_abs_adj[nm]))], marker='o', ms=3, lw=.75,color='grey')
  File "/Users/marc/.local/lib/python2.7/site-packages/matplotlib/__init__.py", line 1870, in inner
    return func(ax, *args, **kwargs)
  File "/Users/marc/.local/lib/python2.7/site-packages/matplotlib/axes/_axes.py", line 1528, in plot
    for line in self._get_lines(*args, **kwargs):
  File "/Users/marc/.local/lib/python2.7/site-packages/matplotlib/axes/_base.py", line 406, in _grab_next_args
    for seg in self._plot_args(this, kwargs):
  File "/Users/marc/.local/lib/python2.7/site-packages/matplotlib/axes/_base.py", line 383, in _plot_args
    x, y = self._xy_from_xy(x, y)
  File "/Users/marc/.local/lib/python2.7/site-packages/matplotlib/axes/_base.py", line 242, in _xy_from_xy
    "have shapes {} and {}".format(x.shape, y.shape))
ValueError: x and y must have same first dimension, but have shapes (3,) and (5,)

**Comment by McBaboulek** [comment]
![velest_final_ruhr](https://user-images.githubusercontent.com/83026886/162558461-e4354d01-44fe-4c00-8139-cb8094149013.png)

**Comment by McBaboulek** [comment]
![path_ruhr](https://user-images.githubusercontent.com/83026886/162558480-0f747981-9465-4a22-9aa8-5566df5d3bcd.png)

**Comment by McBaboulek** [comment]
![velest_analytics_ruhr](https://user-images.githubusercontent.com/83026886/162558613-0d6d3723-bdbd-4700-99e8-3837b62cc6dd.png)

The code could not plot the; Origins time, longitude, latitude, and depth adjustment. the is an error stated from ax1 to ax4

**Comment by McBaboulek** [comment]
![path_ruhr5](https://user-images.githubusercontent.com/83026886/162918465-8034e3e3-bab1-4edb-949c-61102d6bdaf4.png)

**Comment by McBaboulek** [comment]
![path_ruhr5](https://user-images.githubusercontent.com/83026886/162918602-64e58268-96b1-424a-9440-0d292a5eaae8.png)
