### ISSUE TITLE
LatLon

### ISSUE THREAD

**Issue by jeospring** [saeedsltm/PyVelest#6]
Hi, 

I installed all requirements. However, i get this error;

**from LatLon import lat_lon as ll
ImportError: No module named LatLon**

But i already installed LatLon

**pip install LatLon
Requirement already satisfied: LatLon in /usr/local/lib/python3.6/site-packages (1.0.2)
Requirement already satisfied: pyproj in /usr/local/lib/python3.6/site-packages (from LatLon) (2.4.0)**

What do you think about this problem? 
Thank you

**Comment by saeedsltm** [comment]
Dear jeospring

Please try with Python2.X version since i am not sure about 3.X yet.

**Comment by jeospring** [comment]
Thank you for your comment. It worked. Is it possible to use the code for other regions apart from Iran?

**Comment by saeedsltm** [comment]
Dear jeospring

Yes, Just try it,

Regards

On 12/15/19, jeospring <notifications@github.com> wrote:
> Thank you for your comment. It worked. Is it possible to use the code for
> other regions apart from Iran?
>
> --
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub:
> https://github.com/saeedsltm/PyVelest/issues/6#issuecomment-565796664


-- 
Dear

Regards
______________________
Saeed Soltani Moghadam.
PhD student of Earthquake Seismology @ IIEES, Tehran, Iran.
Tel: (+98) 912 075 6095
