### ISSUE TITLE
start.plot_final():IndexError: index 0 is out of bounds for axis 0 with size 0

### ISSUE THREAD

**Issue by cxhost** [saeedsltm/PyVelest#7]
Dear saeedsltm：
PyVelest code is of great use for velest. I try to run your code with your data set, the following error is generated, I appreciate your help. 
Regards.

+++ Enter Project Name: <Please use the name of velocity model you're using>

test

+++ Read VELEST input parameters ...
+++ Write VELEST control file ...
+++ Plotting data statistics ...
+++ Make synthetic velocity models ...
+++ Run VELEST ...
   --- 50 synthetic model(s) found ...
   --- Run for synthetic model: 1
   --- Run for synthetic model: 2
   --- Run for synthetic model: 3
   --- Run for synthetic model: 4
   --- Run for synthetic model: 5
   --- Run for synthetic model: 6
   --- Run for synthetic model: 7
   --- Run for synthetic model: 8
   --- Run for synthetic model: 9
   --- Run for synthetic model: 10
   --- Run for synthetic model: 11
   --- Run for synthetic model: 12
   --- Run for synthetic model: 13
   --- Run for synthetic model: 14
   --- Run for synthetic model: 15
   --- Run for synthetic model: 16
   --- Run for synthetic model: 17
   --- Run for synthetic model: 18
   --- Run for synthetic model: 19
   --- Run for synthetic model: 20
   --- Run for synthetic model: 21
   --- Run for synthetic model: 22
   --- Run for synthetic model: 23
   --- Run for synthetic model: 24
   --- Run for synthetic model: 25
   --- Run for synthetic model: 26
   --- Run for synthetic model: 27
   --- Run for synthetic model: 28
   --- Run for synthetic model: 29
   --- Run for synthetic model: 30
   --- Run for synthetic model: 31
   --- Run for synthetic model: 32
   --- Run for synthetic model: 33
   --- Run for synthetic model: 34
   --- Run for synthetic model: 35
   --- Run for synthetic model: 36
   --- Run for synthetic model: 37
   --- Run for synthetic model: 38
   --- Run for synthetic model: 39
   --- Run for synthetic model: 40
   --- Run for synthetic model: 41
   --- Run for synthetic model: 42
   --- Run for synthetic model: 43
   --- Run for synthetic model: 44
   --- Run for synthetic model: 45
   --- Run for synthetic model: 46
   --- Run for synthetic model: 47
   --- Run for synthetic model: 48
   --- Run for synthetic model: 49
   --- Run for synthetic model: 50
+++ Analyse VELEST outputs ...
+++ Plotting data statistics ...
+++ Minimum model id: 31
+++ Preparing reports ...
+++ Plotting final figures, Please wait ...
Traceback (most recent call last):
  File "PyVelest.py", line 3177, in <module>
    start.plot_final()
  File "PyVelest.py", line 2937, in plot_final
    ax1.scatter(self.st_lon[0],self.st_lat[0],s=0.3*scl,marker='+',color='none',linewidth=1,label='+%.1fsec'%(self.max_rms))
IndexError: index 0 is out of bounds for axis 0 with size 0

**Comment by saeedsltm** [comment]
Dear cxhost,

Which Python version have you tried?

**Comment by arturo-github** [comment]
Hi everyone!

Dear saeedsltm

I  have a very similar error that @cxhost. My error just change in the penultimate line:

.
.
.
+++ Plotting final figures, Please wait ...
Traceback (most recent call last):
File "PyVelest.py", line 3155, in <module>
      start.plot_final()
File "PyVelest.py", line 2922, in plot_final
      ax1.scatter(self.st_lon[0], self.st_lat[0],
IndexError: index 0 is out of bounds for axis 0 with size 0

I am using Python 2.7.18  :: Anaconda.
Cheers!!
