### ISSUE TITLE
PySelect2D.py bad header

### ISSUE THREAD

**Issue by jeospring** [saeedsltm/PyVelest#8]
Hi, 

I tried to select good events to do velest run. However you have much more information in your initial.out file, particularly in 2nd beginning with GAP:

 2016  1 1 0000 20.0 L  35.963  51.994 21.5  SYN 16 0.1                        1
 GAP= 45        0.19       0.5     0.6  1.2 -0.3986E-01 -0.6621E-01 -0.4952E-01E

In my initial.out file, I just have;

 2016 0916 0022 09.9 L  37.594  38.734  9.5  DDA 21 0.2 2.2LDDA                1
 GAP= 55                                1.9                                    E

As you see, some information is missing in my input file. I run PySelect2D.py. I see the error as below;

Traceback (most recent call last):
  File "PySelect2D.py", line 167, in <module>
    OTER   = [float(l[14:20]) for l in i if l[79:80] == 'E']
ValueError: could not convert string to float: T 0000

I remove the lines beginning with OTER, LATER, LONER, DEPER. However I still get the error. How can I fix this problem?

Thank you

**Comment by saeedsltm** [comment]
Dear jeospring:

Before you run the code you need to relocate your initial NORDIC file (your  initial.out) using "hyp" command (hyp is a SEISAN sub-command to do a location/relocation). The output would be "hyp.out" but in this case it has all necessary headers. Rename this file to "initial.out" and then try again.

Regards
